package my:pmod-oled-driver;

world driver {
    // 1. Hardware imports (Internal details)
    import wasi:spi/spi;
    import wasi:gpio/gpio;
    import wasi:delay/delay;
    import my:debug/logging;

    // 2. Public Export (The interface defined in graphics.wit)
    export graphics;
}
