// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_run_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::run();
}
pub trait Guest {
    fn run() -> ();
}
#[doc(hidden)]
macro_rules! __export_world_blinky_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "run")] unsafe extern "C" fn
        export_run() { unsafe { $($path_to_types)*:: _export_run_cabi::<$ty > () } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_blinky_cabi;
#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod host {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() = super::__link_custom_section_describing_imports;
    use super::_rt;
    #[allow(unused_unsafe, clippy::all)]
    pub fn on() -> () {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "host")]
            unsafe extern "C" {
                #[link_name = "on"]
                fn wit_import0();
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0() {
                unreachable!()
            }
            unsafe { wit_import0() };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn off() -> () {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "host")]
            unsafe extern "C" {
                #[link_name = "off"]
                fn wit_import0();
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0() {
                unreachable!()
            }
            unsafe { wit_import0() };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn delay(ms: u32) -> () {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "host")]
            unsafe extern "C" {
                #[link_name = "delay"]
                fn wit_import0(_: i32);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32) {
                unreachable!()
            }
            unsafe { wit_import0(_rt::as_i32(&ms)) };
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_blinky_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_blinky_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_blinky_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:local:demo:blinky:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 216] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\\\x01A\x02\x01A\x04\x01\
B\x05\x01@\0\x01\0\x04\0\x02on\x01\0\x04\0\x03off\x01\0\x01@\x01\x02msy\x01\0\x04\
\0\x05delay\x01\x01\x03\0\x04host\x05\0\x01@\0\x01\0\x04\0\x03run\x01\x01\x04\0\x11\
local:demo/blinky\x04\0\x0b\x0c\x01\0\x06blinky\x03\0\0\0G\x09producers\x01\x0cp\
rocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
