package my:temp-sensor;

interface sensor-app {
    run: func();
}

world guest {
    import wasi:spi/spi;
    import wasi:gpio/gpio;
    import wasi:delay/delay;
    import my:debug/logging; 

    export sensor-app;
}
