package wasi:spi;

interface spi {
    variant error {
        overrun,
        mode-fault,
        frame-format,
        chip-select-fault,

        other(string),
    }

    variant operation {
        read(u64),
        write(list<u8>),
        transfer(list<u8>),
        delay-ns(u32),
    }
    
    variant operation-result {
        read(list<u8>),
        write,
        transfer(list<u8>),
        delay,
    }

    enum mode {
        mode0, // CPOL=0, CPHA=0
        mode1, // CPOL=0, CPHA=1
        mode2, // CPOL=1, CPHA=0
        mode3  // CPOL=1, CPHA=1
    }

    record config {
        frequency: u32,
        mode: mode,
        lsb-first: bool,
    }

    resource spi-device {
        configure: func(config: config) -> result<_, error>;
        read: func(len: u64) -> result<list<u8>, error>;
        write: func(data: list<u8>) -> result<_, error>;
        transfer: func(data: list<u8>) -> result<list<u8>, error>;
        transaction: func(operations: list<operation>) -> result<list<operation-result>, error>;
    }

    get-device-names: func() -> list<string>;
    open-device: func(name: string) -> result<spi-device, error>;
}

world wasi-spi-host {
    import spi;
}
